### PR TITLE
fix#23: IE support

### LINKED ISSUE #23: IE support
Hi guys!

We are having some issues with Internet Explorer. [Object.assign](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign) is not supported in Explorer. And _"assigning"_ objects like [here](https://github.com/continuationlabs/credit-card/blob/master/lib/index.js#L90) and [here](https://github.com/continuationlabs/credit-card/blob/master/lib/index.js#L238) are causing _Syntax Error_ in all versions of Explorer.

Will you accept a PR to fix this issues?

### PR DESCRIPTION
**Pull request by eloypnd**
fix #23

### CODE REVIEW

**Comment by arb** [comment]
@eloypnd thanks for your interest in credit-card. It's cool to hear you are using it on the client. You're correct, this module uses ES2015 features that not all the browsers natively support as the original execution context for this module is Node 4.

We (Continuation Labs) really don't want to get into the business of publishing transpiled code for several reasons.
1. It's just a pain to manage.
2. It's weird to test because you're testing es2015 code that works fine on Node, but people and up using transpiled babel code on the client that isn't tested at all.
3. You become deponent on the babel ecosystem which has had some serious bumps during the 5.x.x to 6.x.x transition.
4. By not using the actual source, you lose a lot of optimization flexibility from within webpack/browserify

I'm not sure which tool you are using, but I'm going to make a few assumptions. You're using either browserify or webpack and have babel running for your code but are excluding node_modules for performance reasons. I would suggest allowing babel to run on a whitelist of node modules and handle the transpilation in the tools your front end is already using.

If you're using webpack and have more questions, I'd be happy to help you with setting up configurations for this. If you're using something else, you'll have to ask elsewhere I'm afirad :smile: 

Related issue - https://github.com/continuationlabs/reach/pull/2

**Comment by eloypnd** [comment]
Thanks for your answer @arb.

In this case I think I will go for now with a simple luhn check for the credit card number, that'll do the trick :)

P.D.: just my two cents, if don't plan to support browsers, just node, maybe it will help to specify it in the beginning of the readme ;)

**Comment by alterx** [comment]
@arb I've been trying to play around with the include/exclude functionality of webpack's babel loader with no success, maybe you could provide some guidance in how to configure it to compile this specific module, but exclude everything else.

I love the flexibility of this module and would love to use it in my project, thanks in advance.

**Comment by arb** [comment]
So what I would probably do is use the `include` feature and set it to a function, then you can examine the absolute path that's passed in and return either `true` or `false`. So in your case, you'd want to return `true` for all your code, plus this node module as well. 

While this may be a pain, us publishing source rather than a transpiled version actually gives you more bundle optimization options that you would otherwise lose if we just published the transpiled versions.

**Comment by alterx** [comment]
I didn't know you could also use a function, I guess you learn something new every day.

For those interested in the solution I implemented I simply added:
`
include: function(absPath){
    return (/credit-card/.test(absPath) || /src/.test(absPath));
  },
`

instead of the original `exclude: /node_modules/,` I had, thanks @arb

**Pull request closed without merging**
