### PR TITLE
Allow the module to be used without --harmony flag

### PR DESCRIPTION
**Pull request by thomasguillory**
`let` keyword is not available yet in node 4.0.0, so this module is unusable
in that environment without --harmony flag.

### CODE REVIEW

**Comment by cjihrig** [comment]
`let`/`const` is available in Node v4. Even if it wasn't, this module depends on `Reach` which uses `let`/`const`. Thanks for the PR though!

**Comment by thomasguillory** [comment]
@cjihrig my mistake, sorry. Uglifyjs is whinning on your module `let` keywords :/

**Comment by cjihrig** [comment]
Are you trying to uglify for use in the browser?

**Comment by arb** [comment]
You have to run credit-card through a transpiler before UglifyJS. UglifyJS, at least as of this moment, has 0 support for any of the es2015 features. My guess is you are excluding all of node_modules in your build step?

**Pull request closed without merging**
